Import("qtEnv dup")

qtEnv.EnableQt4Modules(['QtCore','QtGui'])

if dup == 0: qtEnv.Append(CPPPATH=['.', '#build_dup0'])
qtEnv.Program('aaa', 'aaa.cpp', 
              QT4_MOCHPREFIX = 'moc_',
              QT4_MOCHSUFFIX = '.cc')
