#!/usr/vin/env python
# coding=utf-8

import os

def image(target, source, env):
    """Generate an image for testing.
    """
    import numpy
    import matplotlib.pyplot
    xx = numpy.linspace(0, numpy.pi, 1000)
    fig = matplotlib.pyplot.figure(figsize=(8,5))
    axs = fig.add_subplot(1,1,1)
    for II in range(5):
        label = "$sin({0:d}\pi)$".format(II)
        axs.plot(xx, numpy.sin(II * xx), label=label)

    axs.legend(loc="lower left")
    axs.set_xlabel("Time [s]")
    axs.set_ylabel("Signal")
    axs.set_title("Look!  A pretty graph!")
    fig.savefig(str(target[0]))
    return


env = Environment(ENV=os.environ, tools=["default", "pandoc"])
env.AppendUnique(BUILDERS={"image" : Builder(action=image)})

srcs = ["example." + x for x in ("md", "yaml")]

img = env.image("example.png", [])
html = env.Pandoc("example.html", srcs,
                  PANDOCFLAGS="--bibliography example-args.bib")

