#
# A simple SConstruct for creating PDF files from Docbook XML
# sources. It's plain and ugly...but does its job ;).
#

#
# Copyright (c) 2001-2010 The SCons Foundation
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
# KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


import os

bld_fo = Builder(action = 'xsltproc ./pdf.xsl $SOURCE > $TARGET',
                 suffix = '.fo',
                 src_suffix = '.xml',
                 single_source = True)

bld_html = Builder(action = 'xsltproc ./html.xsl $SOURCE > $TARGET',
                 suffix = '.html',
                 src_suffix = '.xml',
                 single_source = True)

bld_pdf = Builder(action = 'fop $SOURCE $TARGET',
                 suffix = '.pdf',
                 src_suffix = '.fo',
                 single_source = True)

env = Environment(ENV = os.environ,
                  BUILDERS = {'Fo' : bld_fo,
                              'Html' : bld_html,
                              'Pdf' : bld_pdf})

env.Pdf('manual', env.Fo('manual'))
env.Pdf('reference', env.Fo('reference'))

env.Html('manual','manual')
env.Html('reference','reference')

